config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  resources :articles do
    resources :comments  
  end

  get "/tags", to: "articles#getTags"
  
  get "/admin", to: "admin#admin"

  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy  
  has_and_belongs_to_many :tags, :uniq => true
  has_and_belongs_to_many :users
  validates :title, presence: true, length: { minimum: 5 }
  mount_uploader :thumbnail, ThumbnailUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :articles, :uniq => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_and_belongs_to_many :articles
  validates :first_name, :presence => true
  validates :last_name, :presence => true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :deny_access, :unless => :is_admin?
  def admin
    @tags = Tag.all
  end
  
  def new_tag
    @tag = Tag.new(tag_params)
  end
  
  protected

  def is_admin?
    user_signed_in? && current_user.role == 'admin'
  end
  
  private
  
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]
    
    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update){
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
  
  def deny_access
    redirect_to('/')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @otherArticles = Article.order("created_at").last(5)
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @tags = params[:tags]
    @article.tags.destroy_all
    if @tags != "" #catch no tags
      tagsArray = @tags.split(",")
      tagsArray.each do |tag|
        tagObj = Tag.find(tag)
        @article.tags << tagObj
      end
    end
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def getTags
    @query = params[:name]
    @tags = Tag.where("name LIKE ?", "%#{@query}%").all
    render :json => @tags
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :summary, :tags, :thumbnail, :remote_thumbnail_url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy #TODO set up to only allow commenter or admin to destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @latestArticles = Article.order("created_at").last(4)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/User/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admin/admin.html.erb
<div class = "container">
	<h1>Administration</h1>
	<p>
		This is the admin page.
	</p>
	<h3>Manage Article Tags</h3>
	<div id = "listTags" class = "list-group">
		<% @tags.each do |tag| %>
		<div class = "list-group-item clearfix">
			<div>
				<%= tag.text %>
				<%= link_to 'Edit', edit_article_path(article) %>
				<%= link_to 'Destroy', article_path(article),
				method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
		</div>
		<% end %>
	</div>
	<%= submit_tag 'New tag', {class: "newTagLink", type: "button", data: {newtag: ''}} %>
</div>

app/views/articles/_form.html.erb
<%= form_for @article, :html => {:multipart => true} do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
	<h4><%= pluralize(@article.errors.count, "error") %> prohibited
	this article from being saved:</h4>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class = "form-group">
	<%= f.label :title %>
	<br>
	<%= f.text_field :title, class: "form-control" %>
</div>

<div class = "form-group">
	<%= f.label :summary %>
	<br>
	<%= f.text_area :summary, class: "form-control" %>
</div>

<div class = "form-group">
	<%= f.label :thumbnail %>
	<br>
	<%= f.file_field :thumbnail, class: "form-control" %>
</div>

<div class = "form-group">
	<%= f.label :remote_thumbnail_url, "or image URL" %>
	<br>
	<%= f.text_field :remote_thumbnail_url, class: "form-control" %>
</div>

<div class = "form-group">
	<%= f.label :text %>
	<br>
	<%= f.text_area :text, id: "article_text", class: "form-control" %>
</div>

<%= content_tag "div", id:"divTags", class: "form-group", data: { tags: @article.tags } do%>
	<%= f.label :tags %>
	<br />
	<%= text_field_tag "tags", nil, placeholder: "Add tags", id: "auto_complete", class: "form-control" %>
<% end %>
<div>
	<p>
		<%= f.submit %>
	</p>
</div>
<% end %>

app/views/articles/edit.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-lg-9">
			<div class="panel panel-default">
				<div class = "panel-body">
					<div class = "page-header">
						<h3>Editing Article</h3>
					</div>
					<%= render 'form' %>
				</div>
			</div>
			<%= link_to 'Back', articles_path %>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class = "container">
	<h1>Listing articles</h1>
	<div class = "row">
		<div class = "col-lg-10">
			<div class = "list-group">
				<% @articles.each do |article| %>
				<div class = "list-group-item clearfix">

					<h4 class = "list-group-item-heading"><%= link_to article.title, article_path(article) %></h4>
					<div id="divThumbnail" >
						<%= image_tag article.thumbnail.url(:thumb).to_s, alt: "article image", class: "featureImg" if article.thumbnail?%>
					</div>
					<p>
						<%= article.summary %>
					</p>
					<% if user_signed_in? %>
					<% if current_user.role == "admin" then %>
					<div id = "divArticleOptions" >
						<%= link_to 'Edit', edit_article_path(article) %>
						<%= link_to 'Destroy', article_path(article),
						method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
					<% end %>
					<% end %>
				</div>
				<% end %>
			</div>
			<% if user_signed_in? %>
			<% if current_user.role == "admin" then %>
			<%= link_to 'New article', new_article_path %>
			<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-lg-9">
			<div class="panel panel-default">
				<div class = "panel-body">
					<div class = "page-header">
						<h3>New Article</h3>
					</div>
					<%= render 'form' %>
				</div>
			</div>
			<%= link_to 'Back', articles_path %>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class = "container">
	<div class = "row">
		<div class = "col-lg-9">
			<div class="panel panel-default">
				<div class = "panel-body">
					<div class = "page-header">
						<h3><%= @article.title %></h3>
					</div>
					<%= image_tag @article.thumbnail.url().to_s, alt: "article image", class: "featureImg" if @article.thumbnail?%>
					<p>
						<%= raw @article.text %>
					</p>
					<p>
						<h4>Tagged in:</h4>
						<ul>
						<% @article.tags.each do |tag| %>
							<li><%= tag.name %></li>
						<% end %>
						</ul>
					</p>
				</div>
			</div>
			<div class="panel panel-default">
				<div class = "panel-body">
					<div class = "page-header">
						<h3>Comments</h3>
					</div>
					<%= render @article.comments%>
					<% if user_signed_in? %>
					<h4>Add a comment:</h4>
					<%= render "comments/form" %>
					<% else %>
					<h4>
						You must be signed in to comment.
					</h4>
					<% end %>
				</div>
			</div>
			<%= link_to 'Back to all articles', articles_path %>
			<% if user_signed_in? %>
			<% if current_user.role == "admin" then %>
			<%= link_to 'Edit', edit_article_path(@article) %>
			<% end %>
			<% end %>
		</div>
		<div class = "col-lg-3">
			<div class = "list-group">
				<div class = "list-group-item">
					<h3>Recent Posts</h3>
				</div>
			</div>
			<div class = "list-group">
				<% @otherArticles.reverse_each do |otherArticle| %>
				<a href = "#" class = "list-group-item"> <h4 class = "list-group-item-heading"><%= otherArticle.title %></h4>
				<p class = "list-group-item-text">
					<%= truncate(otherArticle.summary, :length => 300, :separator => ' ') %>
				</p> </a>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.first_name + ' ' + comment.user.last_name %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
  	<%= f.label 'commenter', 'Commenting as:'%> <br/>
  	<%= current_user.first_name + " " + current_user.last_name%>
  </p>
  <p>
    <%= f.label :body, 'Comment' %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body class="<%= controller_name %> <%= action_name %>">
		<div class="navbar navbar-inverse navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<%= link_to 'Drew Smith\'s Blog', {:controller => "/welcome", :action => "index"}, {:class => "navbar-brand"} %>
					<button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse navHeaderCollapse">
					<ul class="nav navbar-nav navbar-right">
						<li>
							<%= link_to 'Home', {:controller => "/welcome", :action => "index"} %>
						</li>
						<li>
							<%= link_to 'Blog', {:controller => "/articles", :action => "index"} %>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Social Media <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Twitter</a>
								</li>
								<li>
									<a href="#">Facebook</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="#">About</a>
						</li>
						<li>
							<a href="#contact" data-toggle="modal">Contact Me</a>
						</li>

						<% if user_signed_in? %>
						<li>
							<%= link_to current_user.first_name, edit_user_registration_path, :class => 'navbar-link' %>
						</li>
						<li>
							<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
						</li>
						<% else %>
						<li>
							<a href="#register" data-toggle="modal">Sign up</a>
						</li>
						<li>
							<a href="#login" data-toggle="modal">Log in</a>
						</li>
						<% end %>

					</ul>
				</div>
			</div>
		</div>
		<p class="notice" hidden> <%# will deal with these later %>
			<%= notice %>
		</p>
		<p class="alert" hidden>
			<%= alert %>
		</p>
		<%= yield %>

		<div class="navbar navbar-inverse navbar-fixed-bottom">
			<div class="container">
				<p class="navbar-text pull-left">
					Site built by Drew Smith
				</p>
				<a class="navbar-btn btn-primary btn pull-right">Contact Me!</a>
			</div>
		</div>

		<div class="modal fade" id = "contact" role = "dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<form class = "form-horizontal">
						<div class="modal-header">
							<h4>Contact Me</h4>
						</div>
						<div class="modal-body">
							<div class = "form-group">
								<label for = "txtContact-Name" class = "col-lg-2 control-label">Name:</label>
								<div class = "col-lg-10">
									<input class = "form-control" type = "text" id = "txtContact-Name" placeholder="Full Name" />
								</div>
							</div>
							<div class = "form-group">
								<label for = "txtContact-Email" class = "col-lg-2 control-label">Email:</label>
								<div class = "col-lg-10">
									<input class = "form-control" type = "email" id = "txtContact-Email" placeholder="Email" />
								</div>
							</div>
							<div class = "form-group">
								<label for = "txtContact-Msg" class = "col-lg-2 control-label">Message:</label>
								<div class = "col-lg-10">
									<textarea class="form-control" id="txtContact-Msg" rows="8"></textarea>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<a class="btn btn-default" data-dismiss="modal">Close</a>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="modal fade" id = "login" role = "dialog">
			<div class="modal-dialog">
				<div class = "modal-content">
					<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form-horizontal"} ) do |f| %>
					<div class="modal-header">
						Log in
					</div>
					<div class = "modal-body">
						<div class="form-group field">
							<%= f.label :email, class: "col-lg-2 control-label" %>
							<div class = "col-lg-10">
								<%= f.email_field :email, autofocus: true, class: "form-control" %>
							</div>
						</div>

						<div class="form-group field">
							<%= f.label :password, class: "col-lg-2 control-label" %>
							<div class = "col-lg-10">
								<%= f.password_field :password, autocomplete: "off", class: "form-control" %>
							</div>
						</div>

						<% if devise_mapping.rememberable? -%>
						<div class = "form-group">
							<div class = "col-lg-offset-2 col-lg-10">
								<div class="checkbox">
									<label> <%= f.check_box :remember_me %> Remember me </label>
								</div>
							</div>
						</div>
						<div class = "form-group">
							<div class = "col-lg-offset-2 col-lg-10">
								<a href="#register" data-dismiss="modal" data-toggle="modal">Not a member?</a><br/>
								<%= link_to "Forgot your password?", new_password_path(resource_name) %>
							</div>
						</div>
						<% end -%>
						<div class="actions modal-footer">
							<%= f.submit "Log in", class: "btn btn-primary" %>
							<a class="btn btn-default" data-dismiss="modal">Close</a>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fade" id="register" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "form-horizontal"}) do |f| %>
					<div class="modal-header">
						Sign up
					</div>
					<div class="modal-body">
						<%= devise_error_messages! %>						
						<div class="form-group field">
							<%= f.label :first_name, class: "col-lg-3 control-label"   %>
							<div class="col-lg-9">
								<%= f.text_field :first_name, autofocus: true, class: "form-control" %>
							</div>
						</div>
						
						<div class="form-group field">
							<%= f.label :last_name, class: "col-lg-3 control-label"   %>
							<div class="col-lg-9">
								<%= f.text_field :last_name, autofocus: false, class: "form-control" %>
							</div>
						</div>

						<div class="form-group field">
							<%= f.label :email, class: "col-lg-3 control-label" %>
							<div class="col-lg-9">
								<%= f.email_field :email, autofocus: false, class: "form-control" %>
							</div>
						</div>

						<div class="form-group field">
							<%= f.label :password, class: "col-lg-3 control-label" %>
							<% if @validatable %>
							<em>(<%= @minimum_password_length %> characters minimum)</em>
							<% end %>
							<div class="col-lg-9">
							<%= f.password_field :password, autocomplete: "off", class: "form-control" %>
							</div>
						</div>

						<div class="form-group field">
							<%= f.label :password_confirmation, class: "col-lg-3 control-label" %>
							<div class="col-lg-9">
							<%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
							</div>
						</div>
						
						<div class = "form-group">
							<div class = "col-lg-offset-3 col-lg-9">
								<a href="#login" data-dismiss="modal" data-toggle="modal">Already a member?</a>
							</div>
						</div>

						<div class="modal-footer actions">
							<%= f.submit "Sign up", class: "btn btn-primary" %>
							<a class="btn btn-default" data-dismiss="modal">Close</a>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/welcome/index.html.erb
<div class = "container">
	<div id = "welcomeCarousel" class="carousel slide" data-interval = "5000" data-ride = "carousel">
		<ol class = "carousel-indicators">
			<li data-target = "#welcomeCarousel" data-slide-to = "0" class = "active"></li>
			<li data-target = "#welcomeCarousel" data-slide-to = "1"></li>
			<li data-target = "#welcomeCarousel" data-slide-to = "2"></li>
		</ol>
		<div class = "carousel-inner">
			<div class = "active item">
				<h2>Hello world 1!</h2>
				<div class="carousel-caption">
					<h3>Read more posts:</h3>
					<%= link_to 'My Blog', controller: 'articles'%>
				</div>
			</div>
			<div class = "item">
				<h2>Hello world 2!</h2>
				<div class="carousel-caption">
					<h3>Read more posts:</h3>
					<%= link_to 'My Blog', controller: 'articles'%>
				</div>
			</div>
			<div class = "item">
				<h2>Hello world 3!</h2>
				<div class="carousel-caption">
					<h3>Read more posts:</h3>
					<%= link_to 'My Blog', controller: 'articles'%>
				</div>
			</div>
		</div>
		<a class="carousel-control left" href="#welcomeCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#welcomeCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
	</div>
</div>
<div class="container">
	<div class = "row">
		<% @latestArticles.reverse_each do |article| %>
		<div class = "col-md-3">
			<!-- Bootstrap uses a system of twelve total boxes.  The numbers total 12, but you can divide the space how you like -->
			<h3><%= article.title %></h3>
			<p>
				<%= truncate(article.summary, :length => 450, :separator => ' ') %>
			</p>
			<%= link_to 'Read more', article_path(article) %>
		</div>
		<% end %>
	</div>
</div>